### ISSUE TITLE
Enumeration types support

### ISSUE THREAD

**Issue by m-kru** [rggen/rggen#146]
Is there any way to define custom enumeration types using RgGen?

**Comment by taichi-ishitani** [comment]
I think `labels` field is suitable for this purpose.
You can add a name to a bit field value.

https://github.com/rggen/rggen-sample/blob/5955c3bddc2184ece984a608f492beee599e2bfb/block_0.yml#L19

**Comment by taichi-ishitani** [comment]
document for labeled bit field.
https://github.com/rggen/rggen-sample/blob/master/block_0.md#register_1

**Comment by m-kru** [comment]
This falls into separate feature type, namely the value range constraining. Thanks a lot.
