### ISSUE TITLE
separating  HW and SW access

### ISSUE THREAD

**Issue by imerkado91** [rggen/rggen#163]
From my understanding, the attributes of Bit Field are both for HW and SW, is there a way to separate it?
For example, I want it to be RO for HW but RW for SW, Is there a way to do it using the source? if not- can it be added as a new feature?

@arnonsha

**Comment by taichi-ishitani** [comment]
Hi @imerkado91,
How about using the `custom` bit field type?
https://github.com/rggen/rggen/wiki/%27custom%27-bit-field-type

**Comment by taichi-ishitani** [comment]
@imerkado91 
Can you close this issue if you have no further topics?
