### ISSUE TITLE
REGISTER_INDEX

### ISSUE THREAD

**Issue by haridevang** [rggen/rggen#176]
![image](https://github.com/rggen/rggen-sv-rtl/assets/154509358/eb1de171-5fe4-46a6-8b65-43060eb178ef)
Hi, REGISTER_INDEX is used as parameter in the instantiation of the module rggen_default_register but the parameter REGISTER_INDEX is not defined in the module rggen_default_register. 
![image](https://github.com/rggen/rggen-sv-rtl/assets/154509358/3399d017-121c-4c8c-a6e9-b03c3e059d5d)
This creates an issue while running the synthesis.

**Comment by taichi-ishitani** [comment]
I think RgGen which you're using is the previous version.
Can you update RgGen and then generate RTL again?

**Comment by taichi-ishitani** [comment]
@haridevang ,
Is your problem resolved?
