### ISSUE TITLE
YAML specification for custom bit type does not seem to match documentation

### ISSUE THREAD

**Issue by vermea** [rggen/rggen#183]
**Describe the bug**
This is not a code bug but rather what seems like a wiki issue. The [documentation for custom bit types](https://github.com/rggen/rggen/wiki/%27custom%27-bit-field-type) indicates that in YAML format, custom bit types should be defined like this:

`type: [:type, sw_write: set_1, sw_read: clear]`

However, the above results in parsing errors:
`[SyntaxError] (regs.yml): did not find expected node content while parsing a flow node at line 10 column 83`

 It seems that the syntax should rather be:
`type: [custom, sw_write: set_1, sw_read: clear]`

**Comment by taichi-ishitani** [comment]
@vermea ,
Thank you for your report!
I fixed the wiki document.
![image](https://github.com/rggen/rggen/assets/2922232/797ecc7c-6d4c-4c63-8b1e-bd105de51264)
