### ISSUE TITLE
Increase maximum block size to greater than 64KB

### ISSUE THREAD

**Issue by ifthikars** [rggen/rggen#83]
Hi,

I am using your tool to create a RAL model and I get an error that the input byte size 65540 is greater than the maximum byte size  65536.  Is there a way to increase the maximum byte size to larger than 64KB?  Please see the log below.

Best Regards,
Ifthikar

![rggen_RAL_error](https://user-images.githubusercontent.com/87997208/127033887-f74b3d69-2841-4948-9673-ba9de1109dd4.png)

**Comment by taichi-ishitani** [comment]
Hi @ifthikars ,
Thanks for using RgGen!

> Is there a way to increase the maximum byte size to larger than 64KB?

You need to edit your config file and increase the `address_width` value.
https://github.com/rggen/rggen-sample/blob/0f28ca3cdb7781dc87bf4b09546aa0ba4b7e16a4/config.yml#L2

**Comment by ifthikars** [comment]
That worked.  Thanks for the prompt reply.
